import os
import markdown
from xhtml2pdf import pisa

def generate_pdf(markdown_content: str, company_name: str) -> str:
    """Converts a Markdown string to a professional PDF file."""
    
    # Convert markdown to basic HTML
    html_body = markdown.markdown(markdown_content)
    
    # Wrap in full HTML with some CSS styling
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @page {{
                size: A4;
                margin: 2cm;
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                color: #333333;
                line-height: 1.6;
            }}
            h1 {{
                color: #2563eb;
                border-bottom: 2px solid #2563eb;
                padding-bottom: 10px;
                font-size: 24pt;
            }}
            h2 {{
                color: #1e40af;
                margin-top: 25px;
                font-size: 18pt;
            }}
            p {{
                font-size: 12pt;
                margin-bottom: 15px;
            }}
            ul {{
                margin-bottom: 15px;
            }}
            li {{
                font-size: 12pt;
                margin-bottom: 8px;
            }}
            .footer {{
                text-align: center;
                color: #9ca3af;
                font-size: 10pt;
                margin-top: 50px;
                border-top: 1px solid #e5e7eb;
                padding-top: 15px;
            }}
        </style>
    </head>
    <body>
        {html_body}
        <div class="footer">
            Generated by AutoLead AI Workflow Automation | For internal review
        </div>
    </body>
    </html>
    """
    
    # Ensure reports directory exists
    os.makedirs("reports", exist_ok=True)
    
    # Format filename safely
    safe_name = "".join([c for c in company_name if c.isalpha() or c.isdigit() or c==' ']).rstrip()
    safe_name = safe_name.replace(" ", "_").lower()
    pdf_path = f"reports/{safe_name}_audit_report.pdf"
    
    # Create PDF
    with open(pdf_path, "w+b") as result_file:
        pisa_status = pisa.CreatePDF(
            src=html_template,
            dest=result_file
        )
        
    if pisa_status.err:
        raise Exception("Error generating PDF document")
        
    return pdf_path
